name: Build Docker Container & Publish

on:
    release:
        types: [published]

jobs:
    publish_image:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Build DB
              run: |
                  docker build db -t joanferrecid098/questapp-db:latest
                  docker build db -t joanferrecid098/questapp-db:${{ github.event.release.tag_name }}
            - name: Build Backend
              run: |
                  docker build backend -t joanferrecid098/questapp-backend:latest
                  docker build backend -t joanferrecid098/questapp-backend:${{ github.event.release.tag_name }}
            - name: Build Frontend
              run: |
                  docker build frontend -t joanferrecid098/questapp-frontend:latest
                  docker build frontend -t joanferrecid098/questapp-frontend:${{ github.event.release.tag_name }}
            - name: Publish Images
              run: |
                  docker login -u joanferrecid098 -p ${{ secrets.DOCKER_HUB_TOKEN }}
                  docker push joanferrecid098/questapp-db:${{ github.event.release.tag_name }}
                  docker push joanferrecid098/questapp-db:latest
                  docker push joanferrecid098/questapp-backend:${{ github.event.release.tag_name }}
                  docker push joanferrecid098/questapp-backend:latest
                  docker push joanferrecid098/questapp-frontend:${{ github.event.release.tag_name }}
                  docker push joanferrecid098/questapp-frontend:latest
